version: "3.5"


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginix/.
    image: nginx:mi
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:mi
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress:mi
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
networks:
    inception:
      driver: bridge
volumes:
    wordpress:
              driver: local
              driver_opts:
                      device: /home/maboulho/data/wp
                      type: none
                      o: bind
    mariadb:
              driver: local
              driver_opts:
                      device: /home/maboulho/data/db
                      type: none
                      o: bind
  
  